# Generated by Django 5.2.8 on 2025-11-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_site', models.CharField(default='Piauí Tech Hub', max_length=100)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(default='Wilson Sousa', max_length=100)),
                ('titulo_profissional', models.CharField(default='Engenheiro de Software em formação', max_length=100)),
                ('resumo', models.TextField(help_text='Texto curto introdutório')),
                ('biografia_completa', models.TextField(help_text='Texto longo da seção Sobre Mim')),
                ('foto', models.ImageField(blank=True, upload_to='perfil/')),
                ('linkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('ENG', 'Engenharia de Software'), ('TUT', 'Tutoriais'), ('GUIA', 'Guias Completos'), ('TOOL', 'Ferramentas'), ('NEWS', 'Atualidades Tech')], default='NEWS', max_length=4),
        ),
    ]
