# Generated by Django 5.2.8 on 2025-11-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_configuracao_perfil_alter_post_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('ENG', 'Engenharia de Software'), ('TUT', 'Tutoriais'), ('GUIA', 'Guias Completos'), ('TOOL', 'Ferramentas'), ('NEWS', 'Atualidades Tech'), ('ENG', 'Engenharia Geral'), ('DEV', 'Desenvolvimento'), ('ARQ', 'Arquitetura de Software'), ('AGIL', 'Gestão Ágil')], default='NEWS', max_length=4),
        ),
    ]
